### ISSUE TITLE
Release glue 1.4.1

### ISSUE THREAD

**Issue by jimhester** [tidyverse/glue#188]
Prepare for release: 
 
* [x] `devtools::build_readme()` 
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_glue.html) 
* [x] `devtools::check(remote = TRUE, manual = TRUE)` 
* [ ] `devtools::check_win_devel()` 
* [ ] `rhub::check_for_cran()` 
* [ ] `rhub::check(platform = 'ubuntu-rchk')` 
* [ ] `rhub::check_with_sanitizers()` 
* [x] `revdepcheck::revdep_check(num_workers = 4)` 
* [x] Update `cran-comments.md` 
* [ ] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) 
* [ ] Review pkgdown reference index for, e.g., missing topics 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('patch')` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [ ] `usethis::use_dev_version()`

**Comment by billmclellan** [comment]
issue installing glue with r 4.0, worked with 3.6 Error 127 ERROR: compilation failed for package 'glue'

install.packages("glue", dependencies = TRUE)
Installing package into ‘C:/Users/wmclellan/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
     binary source needs_compilation
glue  1.4.0  1.4.1              TRUE

installing the source package ‘glue’

trying URL 'https://cran.rstudio.com/src/contrib/glue_1.4.1.tar.gz'
Content type 'application/x-gzip' length 98581 bytes (96 KB)
downloaded 96 KB

* installing *source* package 'glue' ...
** package 'glue' successfully unpacked and MD5 sums checked
** using staged installation
** libs

*** arch - i386
"c:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c glue.c -o glue.o
sh: c:/rtools40/mingw32/bin/gcc: No such file or directory
make: *** [C:/PROGRA~1/R/R-40~1.0/etc/i386/Makeconf:222: glue.o] Error 127
ERROR: compilation failed for package 'glue'
* removing 'C:/Users/wmclellan/Documents/R/win-library/4.0/glue'
Warning in install.packages :
  installation of package ‘glue’ had non-zero exit status

**Comment by billmclellan** [comment]
devtools::install_github("tidyverse/glue")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘glue’

**Comment by jimhester** [comment]
glue has compiled code, you need to have [Rtools](https://cran.r-project.org/bin/windows/Rtools/) installed in order to install the source package. See [install a source package](https://rstats.wtf/install-a-source-package.html) and how to [setup a source environment](https://rstats.wtf/set-up-an-r-dev-environment.html) for details.

glue is a (indirect) dependency of devtools, so you can't load devtools if glue is not installed. You can use `remotes::install_github("tidyverse/glue")` if needed to install the development version of glue.

You are encountering this because there was recently a new version of glue on CRAN, and the binary version of the package is not yet built. Once the binary is built these problems will resolve themselves.

As none of this are issues in the glue package and this particular release is now on CRAN I am going to close this issue.

If you need further help compiling packages from source or debugging these types of issues <https://community.rstudio.com> is a great place to ask!
